import type { Metadata } from "next";
import "./globals.css";
import MainLayout from "@/components/Layouts/MainLayout";

export const metadata: Metadata = {
  title: "Events | Lets's Build DAO",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <MainLayout>
          <main className="mt-20">{children}</main>
        </MainLayout>
      </body>
    </html>
  );
}
