import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Events | Lets's Build DAO",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <main className="">{children}</main>
      </body>
    </html>
  );
}
